### ISSUE TITLE
[Linux] KDE Plasma getAllScreens bug (maybe others?)

### ISSUE THREAD

**Issue by Vashinator** [Kalmat/PyWinCtl#25]
Hello, as part of trying to use this: https://github.com/tryptech/obs-zoom-and-follow
I ran into the error below.

I noticed this in the readme:
> This module has been tested OK in Ubuntu/Gnome, Ubuntu/Unity, Mint/Cinnamon and Raspbian/LXDE.

I believe these are all DEs based on GTK. KDE Plasma is based on QT.

I have some experience with Python so may be able to help out if you can help get me pointed in the right direction.

```python
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/home/vash/.local/lib/python3.10/site-packages/pywinctl/_pywinctl_linux.py", line 1103, in getAllScreens
[zoom_and_follow_mouse.py]     crtc = DISP.xrandr_get_crtc_info(params.crtc, res.config_timestamp)
[zoom_and_follow_mouse.py]   File "/home/vash/.local/lib/python3.10/site-packages/Xlib/ext/randr.py", line 739, in get_crtc_info
[zoom_and_follow_mouse.py]     return GetCrtcInfo (
[zoom_and_follow_mouse.py]   File "/home/vash/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
[zoom_and_follow_mouse.py]     self.reply()
[zoom_and_follow_mouse.py]   File "/home/vash/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1389, in reply
[zoom_and_follow_mouse.py]     raise self._error
[zoom_and_follow_mouse.py] Xlib.error.XError: <class 'Xlib.error.XError'>: code = 148, resource_id = 0, sequence_number = 18, major_opcode = 140, minor_opcode = 20
[zoom_and_follow_mouse.py] 
```

**Comment by Kalmat** [comment]
Hi!

If I understood well, you are using KDE,  right? Unfortunately, I didn't test pywinctl on KDE desktops, sorry. I really appreciate your offer to help. Perhaps we could start by eliminating the try-except blocks, so we can have a better idea of what might be happening (I suspect KDE is not compatible with this code... we will see and, if so, we will try to find a workaround). This is the code I'm using, in which I eliminated the try-except blocks. If you are so kind to run it and copy-paste the result, it would be very helpful:

```
import ewmh
import math
from pywinctl import Rect, Point, Size
import Xlib

DISP = Xlib.display.Display()
SCREEN = DISP.screen()
ROOT = SCREEN.root
EWMH = ewmh.EWMH(_display=DISP, root=ROOT)


def getAllScreens():
    result = {}
    for i in range(DISP.screen_count()):
        screen = DISP.screen(i)
        root = screen.root

        res = root.xrandr_get_screen_resources()
        modes = res.modes
        wa = EWMH.getWorkArea() or [0, 0, 0, 0]
        for output in res.outputs:
            params = DISP.xrandr_get_output_info(output, res.config_timestamp)
            crtc = DISP.xrandr_get_crtc_info(params.crtc, res.config_timestamp)

            if crtc and crtc.mode:  # displays with empty (0) mode seem not to be valid
                name = params.name
                if name in result.keys():
                    name = name + str(i)
                id = crtc.sequence_number
                x, y, w, h = crtc.x, crtc.y, crtc.width, crtc.height
                wx, wy, wr, wb = x + wa[0], y + wa[1], x + w - (screen.width_in_pixels - wa[2] - wa[0]), y + h - (screen.height_in_pixels - wa[3] - wa[1])
                # check all these values with physical monitors using dpi, mms or other possible values or props
                # dpiX, dpiY = round(crtc.width * 25.4 / params.mm_width), round(crtc.height * 25.4 / params.mm_height)
                dpiX, dpiY = round(w * 25.4 / screen.width_in_mms), round(h * 25.4 / screen.height_in_mms)
                scaleX, scaleY = round(dpiX / 96 * 100), round(dpiY / 96 * 100)
                rot = int(math.log(crtc.rotation, 2))
                freq = 0
                for mode in modes:
                    if crtc.mode == mode.id:
                        freq = mode.dot_clock / (mode.h_total * mode.v_total)
                        break
                depth = screen.root_depth

                result[name] = {
                    'id': id,
                    'is_primary': (x, y) == (0, 0),
                    'pos': Point(x, y),
                    'size': Size(w, h),
                    'workarea': Rect(wx, wy, wr, wb),
                    'scale': (scaleX, scaleY),
                    'dpi': (dpiX, dpiY),
                    'orientation': rot,
                    'frequency': freq,
                    'colordepth': depth
                }
    return result

print(getAllScreens())
```

Thank you!

**Comment by Kalmat** [comment]
Hi again!

I finally managed to install Kubuntu (not sure if this is the distribution you are using, but it uses KDE). Though my setup is a virtual machine (might behave different than a "real" setup), this is what I got::

```
PLATFORM: linux
Traceback (most recent call last):
  File "/home/kalma/Documents/Proyectos/PycharmProjects/PyWinCtl/src/pywinctl/_pywinctl_linux.py", line 1131, in getAllScreens
    crtc = DISP.xrandr_get_crtc_info(params.crtc, res.config_timestamp)
  File "/home/kalma/.local/lib/python3.10/site-packages/Xlib/ext/randr.py", line 759, in get_crtc_info
    return GetCrtcInfo (
  File "/home/kalma/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/home/kalma/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.XError: <class 'Xlib.error.XError'>: code = 148, resource_id = 0, sequence_number = 26, major_opcode = 141, minor_opcode = 20

SCREEN SIZE: Size(width=1920, height=1080)
ALL WINDOWS ['Desktop — Plasma', 'Desktop — Plasma', 'pywinctl : bash — Konsole', 'Plasma']
ACTIVE WINDOW: pywinctl : bash — Konsole / Box(left=2586, top=222, width=744, height=464)

Traceback (most recent call last):
  File "/home/kalma/Documents/Proyectos/PycharmProjects/PyWinCtl/src/pywinctl/_pywinctl_linux.py", line 1131, in getAllScreens
    crtc = DISP.xrandr_get_crtc_info(params.crtc, res.config_timestamp)
  File "/home/kalma/.local/lib/python3.10/site-packages/Xlib/ext/randr.py", line 759, in get_crtc_info
    return GetCrtcInfo (
  File "/home/kalma/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/home/kalma/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.XError: <class 'Xlib.error.XError'>: code = 148, resource_id = 0, sequence_number = 91, major_opcode = 141, minor_opcode = 20

{'Virtual1': {'id': 87, 'is_primary': False, 'pos': Point(x=1920, y=0), 'size': Size(width=1920, height=1080), 'workarea': Rect(left=1920, top=0, right=3840, bottom=1036), 'scale': (50, 101), 'dpi': (48, 97), 'orientation': 0, 'frequency': 59.962843833185445, 'colordepth': 24}, 'Virtual2': {'id': 89, 'is_primary': True, 'pos': Point(x=0, y=0), 'size': Size(width=1920, height=1080), 'workarea': Rect(left=0, top=0, right=1920, bottom=1036), 'scale': (50, 101), 'dpi': (48, 97), 'orientation': 0, 'frequency': 59.962843833185445, 'colordepth': 24}}
```

As you can see, it actually returns the screens struct with all attributes, here:

`{'Virtual1': {'id': 87, 'is_primary': False, 'pos': Point(x=1920, y=0), 'size': Size(width=1920, height=1080), 'workarea': Rect(left=1920, top=0, right=3840, bottom=1036), 'scale': (50, 101), 'dpi': (48, 97), 'orientation': 0, 'frequency': 59.962843833185445, 'colordepth': 24}, 'Virtual2': {'id': 89, 'is_primary': True, 'pos': Point(x=0, y=0), 'size': Size(width=1920, height=1080), 'workarea': Rect(left=0, top=0, right=1920, bottom=1036), 'scale': (50, 101), 'dpi': (48, 97), 'orientation': 0, 'frequency': 59.962843833185445, 'colordepth': 24}}
`
It's true that it also raises some errors, but this is something expected, since the OS generates a sort of "fake" screens. This is why this part of the code is wrapped in a try-except block.

Let me know your thoughts and, if applies, the result of your own tests!

Thank you again!

**Comment by Kalmat** [comment]
Hi! Removed those tracebacks in new version 0.0.42 (those tracebacks were intentionally there in order to have more info from users who could have problems with other linux setups and combinations, but certainly they can be anoying). Anyway, let me know any comment or issue you may have if you have the chance to test it.
