### ISSUE TITLE
Kind request: getMenu() tutorial

### ISSUE THREAD

**Issue by macdeport** [Kalmat/PyWinCtl#9]
Please provide a tutorial for calling GetMenu() and displaying the resultant sub-menu tree or something like that ;-)
Thanks.

**Comment by Kalmat** [comment]
Hi again!

My apologies since I thought it would be clear enough because format and content of getMenu() output is documented on the README file. Besides, you can print it in a legible format just using json.dumps, like this:

```
npw = getActiveWindow()
menu = npw.menu.getMenu()
print(json.dumps(menu, indent=4, ensure_ascii=False))
```

This would produce this output for "Terminal" app (I'm cutting it off since it's extremely large. I'm attaching the complete file anyway):

```
{
    "Apple": {
        ...
}
{
    "Terminal": {
        "hSubMenu": 3,
        "wID": 64,
        "entries": {
            "Acerca de Terminal": {
                "parent": 3,
                "wID": 65,
                "rect": [0, 0, 225, 19],
                "hSubMenu": 0
            },
            "separator": {},
            "Preferencias…": {
                "parent": 3,
                "wID": 66,
                "rect": [0, 31, 225, 50],
                "hSubMenu": 0
            },
            "Entrada de teclado segura": {
                "parent": 3,
                "wID": 67,
                "rect": [0, 50, 225, 69],
                "hSubMenu": 0
            },
            "Servicios": {
                "parent": 3,
                "wID": 68,
                "rect": [0, 81, 225, 100],
                "hSubMenu": 4,
                "entries": {
                    "Ningún servicio aplicable": {
                        "parent": 3,
                        "wID": 69,
                        "rect": [0, 0, 251, 19]
                    },
                    "Preferencias de los servicios…": {
                        "parent": 3,
                        "wID": 70,
                        "rect": [0, 19, 251, 38]
                    }
                }
            },
            "Ocultar Terminal": {
                "parent": 3,
                "wID": 71,
                "rect": [0, 112, 225, 131],
                "hSubMenu": 0
            },
            "Ocultar otros": {
                "parent": 3,
                "wID": 72,
                "rect": [
                    0,
                    131,
                    225,
                    150
                ],
                "hSubMenu": 0
            },
            "Mostrar todo": {
                "parent": 3,
                "wID": 73,
                "rect": [0, 150, 225, 169],
                "hSubMenu": 0
            },
            "Salir de Terminal": {
                "parent": 3,
                "wID": 74,
                "rect": [0, 181, 225, 200],
                "hSubMenu": 0
            },
            "Salir y mantener ventanas": {
                "parent": 3,
                "wID": 75,
                "hSubMenu": 0
            }
        }
    },
    "Shell": {
        "hSubMenu": 5,
        "wID": 76,
        "entries": {
            "Nueva ventana": {
                "parent": 5,
                "wID": 77,
                "rect": [0, 0, 319, 19],
                "hSubMenu": 6,
                "entries": {
                    "Nueva ventana con perfil - Basic": {
                        "parent": 5,
                        "wID": 78,
                        "rect": [0, 0, 333, 19]
                    },
                    "Nueva ventana con el mismo comando": {
                        "parent": 5,
                        "wID": 79,
                        "rect": [0, 19, 333, 38]
                    },
    ...
}
```

As you can see, every menu item is represented by a dictionary key, which has all information key/values inside.
The result is a nested struct since every sub-menu will have all its sub-items inside, within "entries" key (or none in case it is not a sub-menu, but a "final" menu item).

[test.zip](https://github.com/Kalmat/PyWinCtl/files/8378451/test.zip)

**Comment by macdeport** [comment]
Thank you for this example useful for me and perhaps for some others.

It was OK with the previous vers I believe but the current version 0.0.32 I get:

```Python
Traceback (most recent call last):
  File "/Users/alain/Documents/Logiciels/Developpement/tkinter/pyautogui/pywinctl_demo.py", line 179, in <module>
    menu = npw.menu.getMenu()
  File "/Users/alain/Library/Python/3.9/lib/python/site-packages/pywinctl/_pywinctl_macos.py", line 1363, in getMenu
    if findit(): fillit()
  File "/Users/alain/Library/Python/3.9/lib/python/site-packages/pywinctl/_pywinctl_macos.py", line 1360, in fillit
    subfillit(nameList[1][i][0], sizeList[1][i][0], posList[1][i][0], attrList[1][i][0] if addItemInfo else [],
  File "/Users/alain/Library/Python/3.9/lib/python/site-packages/pywinctl/_pywinctl_macos.py", line 1351, in subfillit
    subfillit(submenu, subSize, subPos, subAttr,
  File "/Users/alain/Library/Python/3.9/lib/python/site-packages/pywinctl/_pywinctl_macos.py", line 1351, in subfillit
    subfillit(submenu, subSize, subPos, subAttr,
  File "/Users/alain/Library/Python/3.9/lib/python/site-packages/pywinctl/_pywinctl_macos.py", line 1351, in subfillit
    subfillit(submenu, subSize, subPos, subAttr,
  File "/Users/alain/Library/Python/3.9/lib/python/site-packages/pywinctl/_pywinctl_macos.py", line 1324, in subfillit
    ref = section.replace(SEP + "entries", "") + SEP + name
TypeError: can only concatenate str (not "list") to str

```

**Comment by Kalmat** [comment]
HI! and sorry for the delay in my reply. I was trying to fix this bug. I don't think it has never worked... I bet you have tested this with Path Finder, right? (PF it's going to become my nemesis! HAHAHAHAHAHA!). Path Finder (or similar) has 6 menu levels! My code was working fine with menus with up to 4 levels. There was a "hidden" issue beyond that. It's fixed now (I hope, because menu ouput from Apple Script is a heck of a nightmare!!!!).

I am replying to the other issue as well, so I will upload a new version with both issues.

Thank you again!

**Comment by macdeport** [comment]
> I bet you have tested this with Path Finder, right? (PF it's going to become my nemesis! HAHAHAHAHAHA!). Path Finder (or similar) has 6 menu levels! 

You win :-) but alas the challenging PF is the skeleton of my workflow :-) 
Thank you for your all your perseverance.

**Comment by Kalmat** [comment]
Thank YOU for your interest and help!

HAHAHAHA! I knew it! Thanks god you are using PF, or many "hidden" bugs would still be out there!
